steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "gcr.io/$PROJECT_ID/skylabs-web:$COMMIT_SHA",
      "."
    ]
images:
  - "gcr.io/$PROJECT_ID/skylabs-web:$COMMIT_SHA"
options:
  machineType: "E2_SMALL"