steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/skylabs-web-main:$COMMIT_SHA"
      - "."
    id: Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/skylabs-web-main:$COMMIT_SHA"
    id: Push
images:
  - "gcr.io/$PROJECT_ID/skylabs-web-main:$COMMIT_SHA"
options:
  machineType: "E2_SMALL"
